### ISSUE TITLE
urdfpy does not work

### ISSUE THREAD

**Issue by JojoSim0n** [huy-ha/pybullet-blender-recorder#2]
im triing to run the example code on my ubuntu 18.04, python3 version 3.8.5 and receive the error message: `Traceback (most recent call last):
  File "/home/johannes/Dokumente/pybullet_blender_recorder/demo.py", line 1, in <module>
    from pyBulletSimRecorder import PyBulletRecorder
  File "/home/johannes/Dokumente/pybullet_blender_recorder/pyBulletSimRecorder.py", line 5, in <module>
    from urdfpy import URDF
  File "/home/johannes/.local/lib/python3.10/site-packages/urdfpy/__init__.py", line 1, in <module>
    from .urdf import (URDFType,
  File "/home/johannes/.local/lib/python3.10/site-packages/urdfpy/urdf.py", line 7, in <module>
    import networkx as nx
  File "/home/johannes/.local/lib/python3.10/site-packages/networkx/__init__.py", line 100, in <module>
    import networkx.classes.filters
  File "/home/johannes/.local/lib/python3.10/site-packages/networkx/classes/__init__.py", line 1, in <module>
    from .graph import Graph
  File "/home/johannes/.local/lib/python3.10/site-packages/networkx/classes/graph.py", line 23, in <module>
    from collections import Mapping
ImportError: cannot import name 'Mapping' from 'collections' (/usr/lib/python3.10/collections/__init__.py)`

**Comment by huy-ha** [comment]
From your stack trace, it looks like you're using python 3.10. Also it seems like the errors are from urdfpy, not this repo. I would raise an issue in [that repo](https://github.com/mmatl/urdfpy/issues).
